In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [3]:
train_df = pd.read_csv("../dataset/processed/train_clean.csv")
test_df = pd.read_csv("../dataset/processed/test_clean.csv")

print(train_df.shape)
print(test_df.shape)

(82332, 45)
(175341, 45)

In [4]:
train_df.columns
train_df.drop("id", axis=1, inplace=True)
test_df.drop("id", axis=1, inplace=True)
train_df.columns

Index(['dur', 'proto', 'service', 'state', 'spkts', 'dpkts', 'sbytes',
       'dbytes', 'rate', 'sttl', 'dttl', 'sload', 'dload', 'sloss', 'dloss',
       'sinpkt', 'dinpkt', 'sjit', 'djit', 'swin', 'stcpb', 'dtcpb', 'dwin',
       'tcprtt', 'synack', 'ackdat', 'smean', 'dmean', 'trans_depth',
       'response_body_len', 'ct_srv_src', 'ct_state_ttl', 'ct_dst_ltm',
       'ct_src_dport_ltm', 'ct_dst_sport_ltm', 'ct_dst_src_ltm',
       'is_ftp_login', 'ct_ftp_cmd', 'ct_flw_http_mthd', 'ct_src_ltm',
       'ct_srv_dst', 'is_sm_ips_ports', 'attack_cat', 'label'],
      dtype='str')

In [6]:
categorical_cols = train_df.select_dtypes(include="object").columns

print(categorical_cols)

Index(['service', 'state', 'attack_cat'], dtype='str')

C:\Users\Sonakshi\AppData\Local\Temp\ipykernel_10696\3487075301.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = train_df.select_dtypes(include="object").columns

In [8]:
from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder(
    handle_unknown="use_encoded_value",
    unknown_value=-1
)

categorical_cols = ["proto", "service", "state"]

train_df[categorical_cols] = encoder.fit_transform(train_df[categorical_cols])

test_df[categorical_cols] = encoder.transform(test_df[categorical_cols])

train_df.head()

,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,sttl,...,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,attack_cat,label
0,0.000011,117.0,0.0,4.0,2,0,496,0,90909.0902,254,...,1,2,0,0,0,1,2,0,Normal,0
1,0.000008,117.0,0.0,4.0,2,0,1762,0,125000.0003,254,...,1,2,0,0,0,1,2,0,Normal,0
2,0.000005,117.0,0.0,4.0,2,0,1068,0,200000.0051,254,...,1,3,0,0,0,1,3,0,Normal,0
3,0.000006,117.0,0.0,4.0,2,0,900,0,166666.6608,254,...,1,3,0,0,0,2,3,0,Normal,0
4,0.000010,117.0,0.0,4.0,2,0,2126,0,100000.0025,254,...,1,3,0,0,0,2,3,0,Normal,0

In [9]:
train_df.head()

,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,sttl,...,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,attack_cat,label
0,0.000011,117.0,0.0,4.0,2,0,496,0,90909.0902,254,...,1,2,0,0,0,1,2,0,Normal,0
1,0.000008,117.0,0.0,4.0,2,0,1762,0,125000.0003,254,...,1,2,0,0,0,1,2,0,Normal,0
2,0.000005,117.0,0.0,4.0,2,0,1068,0,200000.0051,254,...,1,3,0,0,0,1,3,0,Normal,0
3,0.000006,117.0,0.0,4.0,2,0,900,0,166666.6608,254,...,1,3,0,0,0,2,3,0,Normal,0
4,0.000010,117.0,0.0,4.0,2,0,2126,0,100000.0025,254,...,1,3,0,0,0,2,3,0,Normal,0

In [10]:
X_train = train_df.drop(["label", "attack_cat"], axis=1)

y_train = train_df["label"]

X_test = test_df.drop(["label", "attack_cat"], axis=1)

y_test = test_df["label"]

In [11]:
print(X_train.shape)
print(y_train.shape)

print(X_test.shape)
print(y_test.shape)

(82332, 42)
(82332,)
(175341, 42)
(175341,)

In [12]:
X_train_normal = X_train[y_train == 0]
print(X_train_normal.shape)
y_train.value_counts()
print((y_train == 0).sum())
X_train_normal.shape[0]
X_train.to_csv("../dataset/processed/X_train.csv", index=False)

X_test.to_csv("../dataset/processed/X_test.csv", index=False)

X_train_normal.to_csv("../dataset/processed/X_train_normal.csv", index=False)

y_train.to_csv("../dataset/processed/y_train.csv", index=False)

y_test.to_csv("../dataset/processed/y_test.csv", index=False)

(37000, 42)
37000

In [13]:
import os

print(os.listdir("../dataset/processed"))

['test_clean.csv', 'train_clean.csv', 'X_test.csv', 'X_train.csv', 'X_train_normal.csv', 'y_test.csv', 'y_train.csv']

In [14]:
train_df.dtypes

dur                  float64
proto                float64
service              float64
state                float64
spkts                  int64
dpkts                  int64
sbytes                 int64
dbytes                 int64
rate                 float64
sttl                   int64
dttl                   int64
sload                float64
dload                float64
sloss                  int64
dloss                  int64
sinpkt               float64
dinpkt               float64
sjit                 float64
djit                 float64
swin                   int64
stcpb                  int64
dtcpb                  int64
dwin                   int64
tcprtt               float64
synack               float64
ackdat               float64
smean                  int64
dmean                  int64
trans_depth            int64
response_body_len      int64
ct_srv_src             int64
ct_state_ttl           int64
ct_dst_ltm             int64
ct_src_dport_ltm       int64
ct_dst_sport_ltm       int64
ct_dst_src_ltm         int64
is_ftp_login           int64
ct_ftp_cmd             int64
ct_flw_http_mthd       int64
ct_src_ltm             int64
ct_srv_dst             int64
is_sm_ips_ports        int64
attack_cat               str
label                  int64
dtype: object

In [15]:
train_df.to_csv("../dataset/processed/train_encoded.csv", index=False)
test_df.to_csv("../dataset/processed/test_encoded.csv", index=False)

In [16]:
import pandas as pd

train_df = pd.read_csv("../dataset/processed/train_encoded.csv")
test_df = pd.read_csv("../dataset/processed/test_encoded.csv")

In [17]:
X_train = train_df.drop("label", axis=1)
y_train = train_df["label"]

X_test = test_df.drop("label", axis=1)
y_test = test_df["label"]

In [18]:
X_train.select_dtypes(include="object").columns

C:\Users\Sonakshi\AppData\Local\Temp\ipykernel_10696\981028811.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  X_train.select_dtypes(include="object").columns

Index(['attack_cat'], dtype='str')

In [19]:
X_train.select_dtypes(include="object").columns

C:\Users\Sonakshi\AppData\Local\Temp\ipykernel_10696\981028811.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  X_train.select_dtypes(include="object").columns

Index(['attack_cat'], dtype='str')

In [20]:
train_df[["proto", "service", "state"]].head()

   proto  service  state
0  117.0      0.0    4.0
1  117.0      0.0    4.0
2  117.0      0.0    4.0
3  117.0      0.0    4.0
4  117.0      0.0    4.0

In [21]:
train_df[["proto", "service", "state"]].dtypes

proto      float64
service    float64
state      float64
dtype: object